#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Oct 08 13:18:33 PDT 2024
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_Single_Cycle_behav -key {Behavioral:sim_1:Functional:tb_Single_Cycle} -tclbatch tb_Single_Cycle.tcl -view /home/jay/SJSU_EE_Masters/Classes/EE-275-Advanced-Computer-Arch/RISC/tb_shift_add_mult_behav.wcfg -log simulate.log"
xsim tb_Single_Cycle_behav -key {Behavioral:sim_1:Functional:tb_Single_Cycle} -tclbatch tb_Single_Cycle.tcl -view /home/jay/SJSU_EE_Masters/Classes/EE-275-Advanced-Computer-Arch/RISC/tb_shift_add_mult_behav.wcfg -log simulate.log

